from __future__ import annotations

from enum import StrEnum


class SwLevel(StrEnum):
    L1 = "L1"
    L2 = "L2"
    L3 = "L3"


class MappingDirection(StrEnum):
    POSITIVE = "POSITIVE"
    NEGATIVE = "NEGATIVE"
    NEUTRAL = "NEUTRAL"


class UpdateMode(StrEnum):
    LIGHT = "LIGHT"
    MARKET = "MARKET"
    FULL = "FULL"


class MacroThemeType(StrEnum):
    DOMESTIC_AGGREGATE = "DOMESTIC_AGGREGATE"
    POLICY_ENVIRONMENT = "POLICY_ENVIRONMENT"
    OVERSEAS_MAPPING = "OVERSEAS_MAPPING"
    MARKET_STYLE = "MARKET_STYLE"


class MacroEventStatus(StrEnum):
    NEW = "NEW"
    DEVELOPING = "DEVELOPING"
    CONFIRMED = "CONFIRMED"
    RESOLVED = "RESOLVED"
    INVALIDATED = "INVALIDATED"


class MacroEventViewType(StrEnum):
    SOURCE = "SOURCE"
    AGENT = "AGENT"
    MANUAL = "MANUAL"


class ConfidenceLevel(StrEnum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"


class MaterialChangeLevel(StrEnum):
    NONE = "NONE"
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"


class IndustryScenarioBias(StrEnum):
    BULL = "BULL"
    BASE = "BASE"
    BEAR = "BEAR"


class MacroBiasTag(StrEnum):
    LIQUIDITY_DOMINANT = "LIQUIDITY_DOMINANT"
    POLICY_EXPECTATION_DOMINANT = "POLICY_EXPECTATION_DOMINANT"
    FUNDAMENTAL_VALIDATION_DOMINANT = "FUNDAMENTAL_VALIDATION_DOMINANT"
    RISK_APPETITE_RECOVERY = "RISK_APPETITE_RECOVERY"
    EXTERNAL_DISTURBANCE_DOMINANT = "EXTERNAL_DISTURBANCE_DOMINANT"
    DEFENSIVE_PREFERENCE_RISING = "DEFENSIVE_PREFERENCE_RISING"
    PRO_CYCLICAL_TRADING_WARMING = "PRO_CYCLICAL_TRADING_WARMING"
    THEMATIC_RISK_APPETITE_DOMINANT = "THEMATIC_RISK_APPETITE_DOMINANT"


class SourceType(StrEnum):
    NEWS = "NEWS"
    REPORT = "REPORT"
    POLICY = "POLICY"
    MARKET_DATA = "MARKET_DATA"
    INTERNAL_SUMMARY = "INTERNAL_SUMMARY"
    MANUAL = "MANUAL"


class EntityType(StrEnum):
    MACRO_MASTER = "MACRO_MASTER"
    MACRO_THEME = "MACRO_THEME"
    INDUSTRY_THESIS = "INDUSTRY_THESIS"
    COMPANY_CONTEXT = "COMPANY_CONTEXT"
    INTEGRATION_SIGNAL = "INTEGRATION_SIGNAL"


class SignalRunStatus(StrEnum):
    PENDING = "PENDING"
    RUNNING = "RUNNING"
    SUCCEEDED = "SUCCEEDED"
    FAILED = "FAILED"
    CANCELED = "CANCELED"


class SignalSourceType(StrEnum):
    POSTGRES = "POSTGRES"


class EvaluationMode(StrEnum):
    EVENT_STUDY = "EVENT_STUDY"
    FACTOR_IC = "FACTOR_IC"
    PORTFOLIO_BACKTEST = "PORTFOLIO_BACKTEST"
